### ISSUE TITLE
Redirecciona a la página de inicio luego de loguearse.

### ISSUE THREAD

**Issue by ework** [ework/is2-2016-1#17]
Redirecciona a la página de inicio luego de loguearse, si puedes también añade un mensaje de error si las credenciales no son válidas.

http://stackoverflow.com/questions/34331478/angular2-redirect-to-login-page

**Importante**
Vamos a trabajar las ramas de la siguiente forma.
Supongamos que este es el Issue #1000 y mi nombre es Juanito lo que debes hacer es:
- Para realizar una nueva tarea, cambiarnos a la rama master.
- git checkout master
- Actualizar todas las ramas
- git pull
- Crear nuestra propia rama
- git checkout -b Issue#1000-Juanito
- Ya en nuestra rama, hacemos los cambios
- git add ...
- git commit -m "..."
- git push origin Issue#1000-Juanito
- Van a la página de git y crean pull request, de mi fork master al nombre de su rama.
- Esto último háganlo con cuidado, no creen el pull request al repo del profesor, eso se hace luego.
- Bueno y lo dejan ahi para que yo lo revice primero.
- Yo siempre voy a dar merge, a menos que les diga que lo hagan ustedes.

**Comment by SebastianWilde** [comment]
Duda:  Ya linkea a la pagina si encuentra al usuario en la base de datos, pero si no lo encuentra da error en la consola, si linkeas un segundo usuario despues, en la pagina de Usuario te apareceran ambos datos, los del primer usuario linkeado y los del segundo.
Con esto termina el issue? no logre lo del mensaje de error. @ework

**Comment by ework** [comment]
Con lo que discutimos por Messenger queda claro, no está mostrando los datos de ambos usuarios sino del usuario anterior, esto se debe a que no cerraste sesión con el otro y por eso no puedes loguear un nuevo usuario.
