### ISSUE TITLE
Instalar el Proyecto

### ISSUE THREAD

**Issue by ework** [ework/is2-2016-1#2]
Instalen el Proyecto, avísenme si tienen problemas.

https://github.com/ework/is2-2016-1

@WilbertAlfonso 
@MeLlamoArroz 
@christianfm10 
@SebastianWilde

**Comment by SebastianWilde** [comment]
Algun IDE  que sugieras?

**Comment by SebastianWilde** [comment]
Algun IDE  que sugieras?

**Comment by christianfm10** [comment]
Daniel, asi tiene que quedar lo de Crear Modelo Usuario?
http://subefotos.com/ver/?961f6359a985479c28045580277908a8o.jpg

**Comment by ework** [comment]
@SebastianWilde 
Para mi los mejores IDE son los de JetBrains. Tienen para Java, Python, etc

Este es el para Java ;)
https://www.jetbrains.com/idea/?fromMenu

Personalmente uso Sublime Text 3.
