### ISSUE TITLE
Crear Modelo Usuario

### ISSUE THREAD

**Issue by ework** [ework/is2-2016-1#4]
AL igual que el semestre anterior, crea un Modelo de usuario y verifica cuando corras el servidor que la tabla que creaste existe.

Usuario:
- Nombre
- Apellido
- Email

Haz sólo lo especificado, lo demás lo hará otro compañero.

Para correr el servidor sudo gradle bootRun.
Para verificar que la tabla se creó puedes usar PgAdmin3.

**Importante**
Vamos a trabajar las ramas de la siguiente forma.
Supongamos que este es el Issue #1000 y mi nombre es Juanito lo que debes hacer es:
- Para realizar una nueva tarea, cambiarnos a la rama master.
- git checkout master
- Actualizar todas las ramas
- git pull
- Crear nuestra propia rama
- git checkout -b Issue#1000-Juanito
- Ya en nuestra rama, hacemos los cambios
- git add ...
- git commit -m "..."
- git push origin Issue#1000-Juanito
- Van a la página de git y crean pull request, de mi fork master al nombre de su rama.
- Esto último háganlo con cuidado, no creen el pull request al repo del profesor, eso se hace luego.
- Bueno y lo dejan ahi para que yo lo revice primero.
- Yo siempre voy a dar merge, a menos que les diga que lo hagan ustedes.

**Comment by christianfm10** [comment]
ScrumMaster, asi tiene que  quedar lo de crear Modelo usuario??

![image](https://cloud.githubusercontent.com/assets/18235596/15085914/e7fa561a-13a2-11e6-9c3e-315e42733e39.png)
@ework

**Comment by christianfm10** [comment]
@ework 
Daniel, asi tiene que quedar lo de Crear Modelo Usuario?
[http://subefotos.com/ver/?961f6359a985479c28045580277908a8o.jpg](url)

**Comment by christianfm10** [comment]
asi tiene que quedar lo de Crear Modelo Usuario?
http://subefotos.com/ver/?961f6359a985479c28045580277908a8o.jpg

**Comment by ework** [comment]
Perfecto,

termina de pushear en tu rama y manda Pull Request.
Este archivo src/main/resources/application.properties nunca debe ser incluido.

Saludos.

**Comment by ework** [comment]
Rechasado PR:

https://github.com/ework/is2-2016-1/pull/10/files

Revisa el Comentario.
