### ISSUE TITLE
Crear un HTML del Login con Bootstrap

### ISSUE THREAD

**Issue by ework** [ework/is2-2016-1#7]
Finalizado el Issue #6 crea en login.html un login para le usuario utilizando bootstrap.

https://getbootstrap.com/examples/signin/

Sólo copia el html, hay otro issue para hacer funcionar el Login.

**Importante**
Vamos a trabajar las ramas de la siguiente forma.
Supongamos que este es el Issue #1000 y mi nombre es Juanito lo que debes hacer es:
- Para realizar una nueva tarea, cambiarnos a la rama master.
- git checkout master
- Actualizar todas las ramas
- git pull
- Crear nuestra propia rama
- git checkout -b Issue#1000-Juanito
- Ya en nuestra rama, hacemos los cambios
- git add ...
- git commit -m "..."
- git push origin Issue#1000-Juanito
- Van a la página de git y crean pull request, de mi fork master al nombre de su rama.
- Esto último háganlo con cuidado, no creen el pull request al repo del profesor, eso se hace luego.
- Bueno y lo dejan ahi para que yo lo revice primero.
- Yo siempre voy a dar merge, a menos que les diga que lo hagan ustedes.

**Comment by MeLlamoArroz** [comment]
Fixed!

**Comment by MeLlamoArroz** [comment]
HTML y CSS
http://es.tinypic.com/r/2j4yij9/9

**Comment by ework** [comment]
Luce bien pero agrégalo al proyecto.
Sólo sigue los pasos, ya hay un html que se llama login, pega ahi tu html.
