### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by ework** [ework/is2-2016-1#8]
Finalizado el Issue #7 , hacer funcionar el Login.

**Importante**
Vamos a trabajar las ramas de la siguiente forma.
Supongamos que este es el Issue #1000 y mi nombre es Juanito lo que debes hacer es:
- Para realizar una nueva tarea, cambiarnos a la rama master.
- git checkout master
- Actualizar todas las ramas
- git pull
- Crear nuestra propia rama
- git checkout -b Issue#1000-Juanito
- Ya en nuestra rama, hacemos los cambios
- git add ...
- git commit -m "..."
- git push origin Issue#1000-Juanito
- Van a la página de git y crean pull request, de mi fork master al nombre de su rama.
- Esto último háganlo con cuidado, no creen el pull request al repo del profesor, eso se hace luego.
- Bueno y lo dejan ahi para que yo lo revice primero.
- Yo siempre voy a dar merge, a menos que les diga que lo hagan ustedes.

**Comment by MeLlamoArroz** [comment]
ucsp.is2.MusicOnlineApplicationTests > testSaveSong FAILED
    java.lang.IllegalStateException
        Caused by: org.springframework.beans.factory.BeanCreationException
            Caused by: org.hibernate.HibernateException

ucsp.is2.MusicOnlineApplicationTests > contextLoads FAILED
    java.lang.IllegalStateException
        Caused by: org.springframework.beans.factory.BeanCreationException
            Caused by: org.hibernate.HibernateException

2 tests completed, 2 failed
:test FAILED


Acá muere el BUILD

**Comment by ework** [comment]
Esa es la página para el login.

src/main/web/app/html

http://localhost:8080/#/login

**Comment by SebastianWilde** [comment]
Problemas con el persist y tenemos que agregar el form del login??

**Comment by SebastianWilde** [comment]
Al correr el programa me sale esto:

/home/sebastian/Documentos/6semestre/IngSoft2/Practica/MusicPlayer/src/main/resources/static/app/service/usuario.service.js
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, stat '/home/sebastian/Documentos/6semestre/IngSoft2/Practica/MusicPlayer/src/main/resources/static/jasmine/unit-tests.html'
    at Error (native)
:gulp_build FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gulp_build'.
> Process 'command '/home/sebastian/Documentos/6semestre/IngSoft2/Practica/MusicPlayer/src/main/web/node/node-v5.11.0-linux-x64/bin/node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 25.018 secs
sebastian@LenovoZ5070:~/Documentos/6semestre/IngSoft2/Practica/MusicPlayer$

**Comment by SebastianWilde** [comment]
Problema solucionado pero aun no funciona

**Comment by SebastianWilde** [comment]
Login termiando
