### ISSUE TITLE
Listar usuarios

### ISSUE THREAD

**Issue by ework** [ework/is2-2016-1#9]
Finalizado el Issue #5 y #6 carga los datos de los usuarios en usuario.html

**Importante**
Vamos a trabajar las ramas de la siguiente forma.
Supongamos que este es el Issue #1000 y mi nombre es Juanito lo que debes hacer es:
- Para realizar una nueva tarea, cambiarnos a la rama master.
- git checkout master
- Actualizar todas las ramas
- git pull
- Crear nuestra propia rama
- git checkout -b Issue#1000-Juanito
- Ya en nuestra rama, hacemos los cambios
- git add ...
- git commit -m "..."
- git push origin Issue#1000-Juanito
- Van a la página de git y crean pull request, de mi fork master al nombre de su rama.
- Esto último háganlo con cuidado, no creen el pull request al repo del profesor, eso se hace luego.
- Bueno y lo dejan ahi para que yo lo revice primero.
- Yo siempre voy a dar merge, a menos que les diga que lo hagan ustedes.

**Comment by WilbertAlfonso** [comment]
@jhneyra @hjneyra  Profesor tengo esta parte de código:

        Statement stmt = null;
		stmt = "Base_Datos".createStatement();
		ResultSet rs = stmt.executeQuery( "SELECT * FROM public.usuario;" );
		return rs;
Se supone debería ejecutar el Query para sacar a todos los usuarios pero donde esta "Base_Datos" debería estar la conexión a la base de datos supone que conectamos en el archivo "application.properties" pero no se como invocar a la conexión desde dentro.
